server:
  port: 8183

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: pmorozov
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    baseline-on-migrate: true

limits:
  min-value: 10000.00
  max-increase: 3000.00
  update-days: 60
